### ISSUE TITLE
Unable to add regular, gas-powered, non-hybrid Volvo

### ISSUE THREAD

**Issue by Pau1ey** [thomasddn/ha-volvo-cars#1]
### The problem

We own 2 regular, non-hybrid/electric Volvos on 2 separate accounts - 2019 XC90 T6 and 2020 XC60 T5.

I created developer account for the XC90 using my existing Volvo Cars login, followed remaining steps creating API, and successfully logged in. I received the below error message in the Volvo Cars integration v0.2.1:

Needs attention

Volvo [VIN]
No devices or entities
Failed setup, will retry: 1 validation error for VolvoCarsVehicle batteryCapacityKWH field required (type=value_error.missing)

### Additional information

I have current subscriptions and are added and working with Volvo On Call integration. I have not tried adding the XC60 into Volvo Cars integration yet. Log is attached below.

### API availability

What does the `API status` sensor report:

* [X] OK
* [ ] Something else (please clarify): 
* [ ] N/A

### Diagnostics

[Volvo Cars Integration Error XC90.txt](https://github.com/user-attachments/files/18082566/Volvo.Cars.Integration.Error.XC90.txt)

**Comment by thomasddn** [comment]
Could you generate the diagnostics file and attach it to this issue? I'm only interested in the `data` element, you may delete everything else.

For the location issue: VOC uses a different API and apparently location is not supported for your vehicle in the API this integration is using. I'll investigate if I can fallback to the VOC API.

**Comment by thomasddn** [comment]
I don't need the diagnostics anymore. I'll add an option so you can choose the unit for the consumption sensor.

I'm unable to see anything in the VOC API because my car is not listed there. Can I register somewhere or is this only US & Canada? There also seems to be no documentation.

**Comment by thomasddn** [comment]
Hi @Pau1ey!

I just released v0.3.0 and you can now configure the desired unit for the fuel consumption.

According to the API documentation, location is only available for:

- XC40 fully electric, model years between 2015 and 2021.
- C40 fully electric, model year 2022.
- XC60, S90, V90, V90CC and XC40, model year 2022.

And in the regions mentioned here: https://developer.volvocars.com/terms-and-conditions/apis-supported-locations/. I can only hope that they will add your vehicle and/or region soon!

**Comment by thomasddn** [comment]
No diagnostics needed for now, all is good!

May I add your name to the readme file for confirming the US and multiple accounts, or do you prefer not to? No hard feelings. ;)
