### ISSUE TITLE
Exception caused by sensor sensor.volvo_FriendlyName_availability

### ISSUE THREAD

**Issue by billraff** [thomasddn/ha-volvo-cars#5]
### The problem
Off and on during the last 24 hours I have seen in the logs that an exception has occurred referencing the sensor sensor.volvo_FriendlyName_availability.
Edit: So these exceptions seem to correspond to when the Volvo app reports ‘Vehicle is in use’.

### API availability

What does the `API status` sensor report:
ValueError: Sensor sensor.volvo_xc90_availability provides state value 'unavailable', which is not in the list of options provided
2024-12-14 09:57:06.822 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()

 
<img width="620" alt="Screenshot 2024-12-14 at 1 31 24 PM" src="https://github.com/user-attachments/assets/c09ae5fc-8a67-4338-9e37-9864b4202bb0" />
 
When the issue is happening the State shows as unavailable rather than one of the options listed for that sensor.
* [ ] N/A

**Comment by thomasddn** [comment]
Thanks for reporting! I'll have a look tomorrow and will provide a fix.

**Comment by thomasddn** [comment]
Should be fixed in v0.3.1! Don't hesitate to reopen if something still isn't working as it should.

**Comment by billraff** [comment]
I installed this morning the new version -
<img width="339" alt="Screenshot 2024-12-16 at 5 02 47 AM" src="https://github.com/user-attachments/assets/bf0d907e-bb15-4d78-ad16-81685eff3f8a" />

but checking the sensor states I don't see unavailable listed as a possible attribute -

<img width="1163" alt="Screenshot 2024-12-16 at 5 02 11 AM" src="https://github.com/user-attachments/assets/441e3207-d813-4126-b426-a022509ab611" />

I looked at sensor.py and didn't see it there either but really not sure if I should ;) 

 VolvoCarsSensorDescription(
        key="availability",
        translation_key="availability",
        api_field="availabilityStatus",
        device_class=SensorDeviceClass.ENUM,
        options=[
            "available",
            "car_in_use",
            "no_internet",
            "power_saving_mode",
            "unspecified",
        ],
        value_fn=_availability_status,
        icon="mdi:radio-tower",



When the car is in use the state returned from the API is unavailable in my experience hence the exception I was receiving. Haven't actually taken the car out yet so will know more later today when the wife takes the girl to school. Thanks.

**Comment by thomasddn** [comment]
The state is indeed not listed in the options, but that is intentionally. If the state is unavailable, a function looks at the reason and takes that reason as the final state.

To be honest, I haven't tested it myself because I wanted to provide a fix quickly. I'll also keep an eye on it later today when I drive home.
