### ISSUE TITLE
Multiple identical exterior images

### ISSUE THREAD

**Issue by thomasddn** [thomasddn/ha-volvo-cars#7]
> Could it be that you have about 5 identical exterior images in HA?

Yes, you are right. Didn't notice it, because I don't need them right now.

_Originally posted by @arboeh in https://github.com/thomasddn/ha-volvo-cars/issues/6#issuecomment-2550949290_

**Comment by thomasddn** [comment]
@arboeh Would you mind going to https://www.volvocars.com/de/account/my-cars/ and copy/paste the URL of the image you see there?

The multiple exterior images are not returned by the API, it's just something I noticed on that page. For my car I can change the query string parameter in the URL given by the API.

For your car, the API returns another format for the image URLs. I can get front and left side images for yours, but I wonder if there are more. Like a front/side view of the car.

**Comment by arboeh** [comment]
It's https://wizz.volvocars.com/images/2024/416/v2/exterior/studio/threeQuartersFrontLeft/transparent_exterior-studio-threeQuartersFrontLeft_5bb83570ff50088bd01d456a593db16d86d9cd5c.png?client=account-app&w=1080&imdensity=1
