### ISSUE TITLE
Average energy consumption (EVs) always unavailable

### ISSUE THREAD

**Issue by arboeh** [thomasddn/ha-volvo-cars#8]
### The problem
The sensor average energy consumption shows "unavailable" for my EV all the time.

### Additional information
Works in Volvo EX30 app.
I can see an entity "averageEnergyConsumptionAutomatic" in the attached diagnostic file with the correct values, but that entity isn't available as sensor.

### API availability
What does the `API status` sensor report:

* [X] OK
* [ ] Something else (please clarify): 
* [ ] N/A

### Diagnostics
[config_entry-volvo_cars-01JFCJSGAKVRMMR1VEV3MR6WMY.json](https://github.com/user-attachments/files/18193550/config_entry-volvo_cars-01JFCJSGAKVRMMR1VEV3MR6WMY.json)

**Comment by thomasddn** [comment]
Apparently the API returns `averageEnergyConsumptionAutomatic` instead of `averageEnergyConsumption` for your model. I'll make sure both fields are checked.

**Comment by arboeh** [comment]
Sorry, still not available.
![Screenshot_20241219-170248](https://github.com/user-attachments/assets/437005ce-971c-4744-83e9-aab877b59475)

**Comment by thomasddn** [comment]
Have you restarted HA after installing the beta v0.3.3-b0? I’m on the road now, but I think the status value in the error message should be uppercase.

**Comment by arboeh** [comment]
Yes, I had to restart the whole system because of Linux Update. The manifest still says 0.3.2. I guess you didn't update it. HACS says 0.3.3-b0. I installed twice, because I thought it's an update prob.
![Screenshot_20241219-171234](https://github.com/user-attachments/assets/3b09cef5-54ee-4b39-af27-02bd6df19575)

**Comment by thomasddn** [comment]
In all my hurry I released the beta yesterday on the same commit of the previous release. So no changes were added! 🤦‍♂️

It should be fixed in b1! Could you give it another try?

Sorry it took so long.

**Comment by arboeh** [comment]
Works.
Long? You are very quick! 🙂👍
